<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="20" hostname="CNL-4JVB6J3" name="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp" tests="22" failures="1" timestamp="20 十二月 2023 03:32:16 GMT" time="2.006" errors="1">
  <testcase name="test015_repricing" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test015_repricing -->
  <testcase name="test016_applyPromotionPlans" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test016_applyPromotionPlans -->
  <testcase name="test021_userAvailableCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test021_userAvailableCoupon -->
  <testcase name="test011_userAvailableCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test011_userAvailableCoupon -->
  <testcase name="test020_queryUserCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test020_queryUserCoupon -->
  <testcase name="test024_queryUserCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test024_queryUserCoupon -->
  <testcase name="test017_promotionDetails_003" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test017_promotionDetails_003 -->
  <testcase name="test029_全场券活动关闭" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test029_全场券活动关闭 -->
  <testcase name="test017_promotionDetails_001" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test017_promotionDetails_001 -->
  <testcase name="test010_queryUserCoupon" time="2.006" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <failure type="java.lang.AssertionError" message="查询用户领券接口返回报错 expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: 查询用户领券接口返回报错 expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp.test010_queryUserCoupon(TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- test010_queryUserCoupon -->
  <testcase name="test028_userAvailableCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test028_userAvailableCoupon -->
  <testcase name="test022_redeemCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test022_redeemCoupon -->
  <testcase name="loginOut" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at UITestCase.BackOffice.login.loginOut(login.java:59)
at E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp.loginOut(TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp.java:436)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </error>
  </testcase> <!-- loginOut -->
  <testcase name="test012_loggedUserReceiveCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test012_loggedUserReceiveCoupon -->
  <testcase name="test025_userAvailableCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test025_userAvailableCoupon -->
  <testcase name="test017_promotionDetails_002" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test017_promotionDetails_002 -->
  <testcase name="test026_loggedUserReceiveCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test026_loggedUserReceiveCoupon -->
  <testcase name="test014_plans" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test014_plans -->
  <testcase name="test023_refundCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test023_refundCoupon -->
  <testcase name="test017_promotionDetails_004" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test017_promotionDetails_004 -->
  <testcase name="test019_userAvailableCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test019_userAvailableCoupon -->
  <testcase name="test018_queryUserCoupon" time="0.000" classname="E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp">
    <skipped/>
  </testcase> <!-- test018_queryUserCoupon -->
</testsuite> <!-- E2E.TestSet_MPMSTORE_MPMSTORE_001_QuanChang_tmp -->
